opensearch-project/opensearch-rs

.ci/opensearch/Dockerfile, .ci/opensearch/opensearch.yml, .github/workflows/test-integrations.yml
Runs the test suite against an OpenSearch Cluster. 
https://github.com/opensearch-project/opensearch-rs/issues/14
=> Adding OpenSearch Support

.ci/functions/wait-for-container.sh, .ci/opendistro/Dockerfile, .ci/opendistro/docker-compose.yml, .ci/opendistro/elasticsearch.yml, .ci/opensearch/Dockerfile, .ci/opensearch/docker-compose.yml, .ci/opensearch/opensearch.yml, .github/workflows/dco.yml, .github/workflows/test-integrations.yml, README.md
Signed-off-by: Aditya Jindal <aditjind@amazon.com>
Runs tests with both the clusters opensearch and opendistro
=> Adding Support to run tests with Opensearch Cluster

.ci/run-opensearch.sh, .ci/run-tests, .github/workflows/test-integrations.yml, yaml_test_runner/src/main.rs
Signed-off-by: Aditya Jindal <aditjind@amazon.com>
Runs the IT test suite against a secured cluster. 
=> Adding Support to run tests with Security

opensearch/Cargo.toml, opensearch/examples/aws_auth.rs, opensearch/src/auth.rs, opensearch/src/http/aws_auth.rs, opensearch/src/http/transport.rs, opensearch/src/lib.rs, opensearch/tests/common/mod.rs, yaml_test_runner/Cargo.toml, yaml_test_runner/src/main.rs, yaml_test_runner/tests/common/client.rs
Implements authenticating requests via AWS SigV4 request signing.
I've taken a first attempt at this using the crate at https://github.com/awslabs/aws-sdk-rust/blob/main/sdk/aws-sigv4. I'm open to any feedback or improvements you might be able to offer on this. Main piece I'm unsure of would be the error handling, so if you can let me know what the desired manner would be, that'd be awesome.
#36
=> Add AWS SigV4 authentication support

COMPATIBILITY.md, api_generator/Cargo.toml, opensearch/Cargo.toml, yaml_test_runner/Cargo.toml
Signed-off-by: Vacha Shah <vachshah@amazon.com>
Bumping the client version to 2.0.0.
#51 
=> Bump client version to 2.0

.github/workflows/links.yml, DEVELOPER_GUIDE.md
Adding a link checker workflow.
_List any issues this PR will resolve, e.g. Closes [...]._ 
=> Adding link checker workflow

MAINTAINERS.md
Be transparent about the fact I now work for Amazon.
=> Correct maintainer affiliation for @xtansia

.github/CODEOWNERS, ADMINS.md, MAINTAINERS.md
- Add @VachaShah as a maintainer
- Correct @aditjind's affiliation
- Update CODEOWNERS to specifically list maintainers
- Update MAINTAINERS.md based off https://github.com/opensearch-project/.github/blob/main/MAINTAINERS.md
=> Add @VachaShah as maintainer

CHANGELOG.md, opensearch/Cargo.toml, opensearch/examples/cat_indices.rs, opensearch/src/http/transport.rs, opensearch/tests/auth.rs, opensearch/tests/common/client.rs, yaml_test_runner/Cargo.toml
Update base64 from ^0.20 to ^0.21
=> Update base64 from ^0.20 to ^0.21

api_generator/Cargo.toml, opensearch/Cargo.toml, yaml_test_runner/Cargo.toml
Signed-off-by: dblock <dblock@amazon.com>
We should be incrementing the version right after release to avoid confusion.
=> Incremented to next developer iteration, 2.1.0.

.ci/functions/imports.sh, .ci/opensearch/Dockerfile, .ci/run-opensearch.sh, .github/workflows/test.yml, CHANGELOG.md, Makefile.toml, opensearch/Cargo.toml, opensearch/tests/cert.rs, opensearch/tests/client.rs, opensearch/tests/error.rs
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>
Update CI to run cargo make test fails out of the box
Follow up on https://github.com/opensearch-project/opensearch-rs/pull/117
=> Update CI to run cargo make test fails out of the box

README.md
Fix README test workflow badge
=> Fix README test workflow badge

guides/index_template.md, opensearch/examples/index_template.rs
=> [CCI] Create index template guide

guides/index_lifecycle.md, opensearch/examples/index_lifecycle.rs
Using the doc: [Opensearch rust](https://docs.rs/opensearch/latest/opensearch/)
- closes #139 
=> [CCI] Create index lifecycle guide

RELEASING.md
Add release instructions to releasing.md
_List any issues this PR will resolve, e.g. Closes [...]._ 
=> Add release instructions

guides/document_lifecycle.md
Added document lifecycle guide
closes #142 
=> Add document lifecycle guide

CHANGELOG.md, DEVELOPER_GUIDE.md
Adds neccessary information to DEVELOPER_GUIDE.md to intialize the project on a clean install.
#184 
=> Adding missing steps to DEVELOPER_GUIDE.md 

MAINTAINERS.md
aditjind's username has changed which caused [link checker failures](https://github.com/opensearch-project/opensearch-rs/actions/runs/8580226271/job/23541391049?pr=245#step:3:83), updating to match new username as shown in https://github.com/opensearch-project/opensearch-rs/graphs/contributors.
=> Correct aditjind's username

CHANGELOG.md
Prepare changelog for 2.3.0 release
=> Prepare changelog for 2.3.0 release

.github/workflows/release-drafter.yml
Reduce minimum release approvers
=> Reduce minimum release approvers

.github/workflows/delete_backport_branch.yml
Fix delete backport branch workflow
=> Fix delete backport branch workflow

jenkins/release.JenkinsFile
Update Jenkins CI/release job docker image
=> Update Jenkins CI/release job docker image

.github/dependabot.yml, .github/workflows/backport.yml, .github/workflows/dependabot_pr.yml, .github/workflows/test.yml
Update upload-artifact and add dependabot for github actions
=> Update upload-artifact and add dependabot for github actions

.github/workflows/backport.yml, .github/workflows/dependabot_pr.yml, CHANGELOG.md
Backports #298 #299 #300 to 2.x
=> [Backport 2.x] GitHub Actions Updates

.github/workflows/test.yml
Attempt to fix failing YAML tests
N/A
=> Attempt to fix failing YAML tests

CHANGELOG.md, opensearch/Cargo.toml, yaml_test_runner/Cargo.toml
=> [Backport 2.x] Update sysinfo requirement from 0.33.0 to 0.34.1 (#331)

.github/workflows/backport.yml, .github/workflows/dependabot_pr.yml, .github/workflows/test.yml
Fix create-github-app-token parameter naming
=> Fix create-github-app-token parameter naming

.github/workflows/backport.yml, .github/workflows/bump-version.yml, .github/workflows/dependabot_pr.yml, .github/workflows/test.yml
=> [Backport 2.x] Bump actions/create-github-app-token from 1 to 2 (#335) 
