.ci/run-opensearch.sh
.github/workflows/test-integrations-unreleased.yml

Signed-off-by: Vacha Shah <vachshah@amazon.com>
Adding workflow and test support to run tests against unreleased OpenSearch versions. This helps in getting the client ready for upcoming releases.
Part of #39 

Add support to run tests against unreleased OpenSearch

---

opensearch/src/auth.rs

This adds an `impl TryFrom<&SdkConfig> for Credentials` to supplement `impl TryFrom<SdkConfig> for Credentials`.
Closes: #62

Add TryFrom<&SdkConfig> for Credentials

---

api_generator/Cargo.toml
api_generator/src/generator/code_gen/mod.rs
api_generator/src/generator/code_gen/params.rs
api_generator/src/generator/code_gen/request/request_builder.rs
opensearch/src/root/mod.rs

Fixes unescaped `<` & `>` chars in generated code docs
Resolves #61 

Fix unescaped chars in docs

---

.ci/DockerFile.Repository
.github/workflows/test-integrations-unreleased.yml
.github/workflows/test-integrations.yml
Makefile.toml

Adds code coverage collection and reporting.
Relates to #73 (but doesn't fully resolve)

Add code coverage collection and reporting

---

.github/workflows/clippy_check.yml

Signed-off-by: Thomas Farr <tsfarr@amazon.com>
Workflows triggered by dependabot run with a restricted readonly github token, as such it does not have permissions to write the clippy-check annotations, as can be seen here: https://github.com/opensearch-project/opensearch-rs/actions/runs/3093397255/jobs/5005721692
https://github.com/opensearch-project/opensearch-rs/actions/runs/3093397255/jobs/5005721692
Package updates should not introduce clippy lints due to not changing code.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-c …

Do not run clippy-check if the branch was pushed by dependabot

---

.github/workflows/changelog_verifier.yml
.github/workflows/test-integrations-unreleased.yml

Disables "Integration with Unreleased OpenSearch (1.x)" job to workaround failure described in #97 

Disable "Integration with Unreleased OpenSearch (1.x)" job

---

.github/workflows/dependabot_pr.yml

Dependabot changelog helper action was failing on our dependabot PRs as the formatting for the titles didn't match the regex used by the action. A fix has been PRd and released https://github.com/dangoslen/dependabot-changelog-helper/pull/113. So updating referenced version here.

Fix dependabot-changelog-helper handling of Rust dependency updates

---

CHANGELOG.md
opensearch/Cargo.toml
opensearch/src/http/transport.rs
yaml_test_runner/Cargo.toml

Update base64 requirement from ^0.13 to ^0.20

Update base64 requirement from ^0.13 to ^0.20

---

.github/workflows/dependabot_pr.yml

Fix dependabot PR workflow race condition in labels.
Workflow will trigger on open before label happens, causing changelog action to do nothing, but is then not re-triggered when the labeling happens.

Fix dependabot PR workflow race condition in labels

---

CHANGELOG.md
opensearch/Cargo.toml
opensearch/src/auth.rs
opensearch/src/http/aws_auth.rs

Bump `aws-*` dependencies from `>= 0.10` to `>= 0.53`
Credential types were split from `aws-types` into `aws-credential-types`
Resolves #106 

Bump `aws-*` dependencies from `>= 0.10` to `>= 0.53`

---

.github/workflows/changelog_verifier.yml
.github/workflows/clippy_check.yml
.github/workflows/delete_backport_branch.yml
.github/workflows/dependabot_pr.yml
.github/workflows/test-integrations-unreleased.yml
.github/workflows/test-integrations.yml
.github/workflows/test.yml
CHANGELOG.md
Makefile.toml
opensearch/Cargo.toml
opensearch/src/lib.rs
opensearch/tests/cert.rs
opensearch/tests/client.rs
opensearch/tests/error.rs
yaml_test_runner/Cargo.toml

Signed-off-by: dblock <dblock@amazon.com>
- Now running unit tests.
- Added OpenSearch 2.4.0.
- Tests pass by default.
Closes https://github.com/opensearch-project/opensearch-rs/issues/45.

Added CI for running unit tests.

---

CHANGELOG.md
USER_GUIDE.md
opensearch/examples/cat_indices.rs
opensearch/src/http/aws_auth.rs
opensearch/src/http/transport.rs
opensearch/src/lib.rs
opensearch/tests/auth.rs
opensearch/tests/aws_auth.rs
opensearch/tests/cert.rs
opensearch/tests/common/client.rs
opensearch/tests/error.rs
yaml_test_runner/Cargo.toml

Signed-off-by: dblock <dblock@amazon.com>
- Lets you configure the service name, defaults to `es` (Managed OpenSearch).
- Always adds a `x-amz-content-sha256` header as per [doc](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/serverless-clients.html). Seems to work against AWS Managed OpenSearch too. 
```rust
let transport = TransportBuilder::new(conn_pool)
.auth(aws_config.clone().try_into()?)
.service_name("aoss")
.build()?;
```
@Xtansia does this look right? I am a rust noob, so no idea if I got the `String` vs. `str` types right here and whether `service_name` is on the right object or whether we can do better. Please tell me what to do + it needs tests & docs.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …

Added support for Amazon OpenSearch Serverless.

---

.github/workflows/test-integrations-unreleased.yml
.github/workflows/test-integrations.yml
.github/workflows/test.yml
CHANGELOG.md

Signed-off-by: Andriy Redko <andriy.redko@aiven.io>
Add cargo cache to Github actions to speed up builds
N/A

Add cargo cache to Github actions to speed up builds

---

.github/CODEOWNERS
MAINTAINERS.md

Adds @reta to MAINTAINERS.md and CODEOWNERS following a vote and unanimous approval by the current maintainers.

Add @reta to MAINTAINERS.md and CODEOWNERS

---

CHANGELOG.md
api_generator/Cargo.toml
api_generator/src/generator/code_gen/mod.rs
api_generator/src/generator/code_gen/url/enum_builder.rs

Bump `syn` from ~1.0 to ~2.0

---

CHANGELOG.md
yaml_test_runner/src/step/match.rs

Fix f64 comparison: use numeric-based comparison instead of string-based
```
'free::search::_260_sort_mixed::search_across_indices_with_mixed_long_and_double_numeric_types' panicked at 'assertion failed: `(left == right)`
left: `Number(1.2233720368547758E18)`,
right: `Number(1.2233720368547758e18)`: expected value json["hits"]["hits"][0]["sort"][0] to match Number(1.2233720368547758e18) but was Number(1.2233720368547758E18)', yaml_test_runner/tests/free/search/_260_sort_mixed.rs:77:5
```
Related to https://github.com/opensearch-project/opensearch-rs/pull/149
For more information on following Developer Certificate of Origin and signing off your commits, please check …

Fix f64 comparison: use numeric-based comparison instead of string-based

---

.ci/opensearch/Dockerfile
yaml_test_runner/Cargo.toml
yaml_test_runner/src/generator.rs
yaml_test_runner/src/main.rs
yaml_test_runner/src/step/comparison.rs
yaml_test_runner/src/step/contains.rs
yaml_test_runner/src/step/do.rs
yaml_test_runner/src/step/is_false.rs
yaml_test_runner/src/step/is_true.rs
yaml_test_runner/src/step/length.rs
yaml_test_runner/src/step/match.rs
yaml_test_runner/src/step/mod.rs
yaml_test_runner/src/step/set.rs
yaml_test_runner/src/step/skip.rs
yaml_test_runner/src/step/transform_and_set.rs

Replaces usages of yaml-rust with serde_yaml, avoids mixing of YAML parsers as well as being more actively maintained and has integration with serde ecosystem. Also now successfully parses at least one more YAML test case that yaml-rust was failing on, but currently needs to be ignored due to issue with numeric indexing of JSON objects.

Use serde_yaml throughout yaml_test_runner instead of yaml-rust

---

USER_GUIDE.md
guides/advanced_index_actions.md
opensearch/examples/advanced_index_actions.rs

Using the doc: [Opensearch rust](https://docs.rs/opensearch/latest/opensearch/)
- closes #140 

[CCI] Create advanced index actions guide

---

.github/CODEOWNERS

Removes aditjind from CODEOWNERS due to their permissions currently being inactive.
This is currently causing an issue with the one-click release workflow approval step: https://github.com/opensearch-project/opensearch-rs/actions/runs/4803532526/jobs/8548110084#step:5:34
This does not revoke their maintainer status, so at such a time they become active again and their permissions are restored they can be re-added to CODEOWNERS for being auto-assigned to reviews.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-or …

Remove aditjind from CODEOWNERS due to their permissions currently being inactive

---

CHANGELOG.md
yaml_test_runner/src/regex.rs
yaml_test_runner/src/step/do.rs
yaml_test_runner/src/step/match.rs
yaml_test_runner/src/step/mod.rs

Fix YAML spec tests by adding u64 (unsigned long) support
N/A

Fixes YAML spec tests by adding u64 (unsigned long) support

---

opensearch/examples/advanced_index_actions.rs
yaml_test_runner/Cargo.toml
yaml_test_runner/skip.yml
yaml_test_runner/src/generator.rs
yaml_test_runner/src/main.rs
yaml_test_runner/src/regex.rs
yaml_test_runner/src/rusty_json.rs
yaml_test_runner/src/step/contains.rs
yaml_test_runner/src/step/do.rs
yaml_test_runner/src/step/match.rs
yaml_test_runner/src/step/mod.rs
yaml_test_runner/src/step/skip.rs
yaml_test_runner/tests/common/client.rs

This fixes several issues with the YAML tests, including those that are currently failing due to the new unsigned data type. This improves the mechanism by which we convert the request bodies into the `json! {}` macro, so that we can avoid doing RegEx replaces on JSON strings. It also adds a hack for the version skip logic due to OS versions "resetting" to "1.0" that meant many test cases were being ignored as they were for ES >= 7.0. Additionally adding logic to cleanup index templates in test teardown so that some of the now running tests pass.
This results in ~300-400 extra test cases now running and passing. (Previously ~800 cases, now ~1200 cases)
For more information on …

Fix CI YAML Tests

---

.github/CODEOWNERS
CHANGELOG.md
MAINTAINERS.md

~Coming from https://github.com/opensearch-project/opensearch-rs/pull/169, re-added @aditjind to CODEOWNERS until they express the desire not to be a maintainer anymore.~
Moved maintainer to emeritus due to inactivity.

Moved @aditjind to emeritus.

---

.github/test-failure-issue-template.md
.github/workflows/test.yml

Add schedule for running YAML tests against unreleased OpenSearch
Fixes #163 

Add schedule for running YAML tests against unreleased OpenSearch

---

CHANGELOG.md
guides/bulk.md

Add bulk guide

---

.github/actions/start-opensearch/action.yml
.github/workflows/test.yml

Bump OpenSearch released version to 2.8.0
N/A

Bump OpenSearch released version to 2.8.0

---

api_generator/Cargo.toml
opensearch/Cargo.toml
yaml_test_runner/Cargo.toml

Using custom version requirements in a library is generally considered a bad idea as it can lead to broken builds downstream.
The cargo docs [goes into this](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-requirements) in the box starting with:
> Recommendation: When in doubt, use the default version requirement operator.
> ...
In this PR I have removed all non-default version requirements.
Happy to discuss if you feel some are needed.
---
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certifi …

Avoid using custom version requirements

---

.github/workflows/version.yml

Add a `version` workflow that gets the current version from the released tag, and then updates modules with a patch bump
https://github.com/opensearch-project/opensearch-rs/issues/69

feature: add auto version bump after release

---

Makefile.toml

Correct the cargo make generate-certs target

Correct the cargo make generate-certs target

---

api_generator/src/bin/run.rs

Set the default branch for download of specifications to `main` instead of `master`
https://github.com/opensearch-project/opensearch-rs/issues/190

set default download branch to main instead of master

---

CHANGELOG.md
opensearch/src/lib.rs
opensearch/src/models/mod.rs

Add a concrete type for the cluster version info, such that clients can parse the json like this:
```rust
client.info().send().await?.json::<ClusterInfo>().await?
```
https://github.com/opensearch-project/opensearch-rs/issues/94

Add cluster version type

---

CHANGELOG.md
USER_GUIDE.md
opensearch/examples/json.rs

Add documentation on how to make raw json  / http requests using the client
https://github.com/opensearch-project/opensearch-rs/issues/193

add raw json requests docs

---

CHANGELOG.md
opensearch/Cargo.toml
opensearch/examples/advanced_index_actions.rs
opensearch/examples/index_lifecycle.rs
opensearch/examples/index_template.rs
opensearch/examples/json.rs
opensearch/src/http/aws_auth.rs
opensearch/src/http/transport.rs
opensearch/src/lib.rs
opensearch/tests/auth.rs
opensearch/tests/aws_auth.rs
opensearch/tests/client.rs
opensearch/tests/common/mod.rs
opensearch/tests/common/server.rs

Update aws-sigv4 to `>= 0.57`
- Expose signing time source as configurable for testability.
- Explicitly add global default headers upfront rather than via reqwest::Client so that they are taken into account for signing.
- Add test cases for sigv4 based off those in opensearch-net.
Fixes #200 

Update aws-sigv4 to `>= 0.57`

---

CHANGELOG.md
api_generator/Cargo.toml
opensearch/Cargo.toml
yaml_test_runner/Cargo.toml

Prepare 2.2.0 release

---

.github/workflows/version.yml

Fix `sed` invocation in version bump workflow

Fix `sed` invocation in version bump workflow

---

api_generator/Cargo.toml
opensearch/Cargo.toml
yaml_test_runner/Cargo.toml

Bump version in `main` to next-in-dev version `3.0.0`

Bump version in `main` to next-in-dev version `3.0.0`

---

api_generator/Cargo.toml
opensearch/Cargo.toml
yaml_test_runner/Cargo.toml

Bump version `2.x` to next-in-dev version `2.3.0`

Bump version in `2.x` to next-in-dev version `2.3.0`

---

api_generator/Cargo.toml
opensearch/Cargo.toml
yaml_test_runner/Cargo.toml

Bump version in `2.2` to next-in-dev version `2.2.1`

Bump version in `2.2` to next-in-dev version `2.2.1`

---

CHANGELOG.md
opensearch/Cargo.toml

There were (erroneously?) published `1.0` versions of some of the dependencies, which caused them to be picked up while they're incompatible with other `aws-` deps

Correctly bound `aws-*` dependency versions

---

CHANGELOG.md
opensearch/Cargo.toml

My previous PR #215 had jumped the gun, and had actually just caught `aws-sdk-rust` mid-release. All the `aws-*` crates we depend on have now been stabilized at `1.0.0` 🎉 🥳 

Stabilize `aws-*` dependencies at `1`

---

CHANGELOG.md
opensearch/Cargo.toml
opensearch/tests/auth.rs
opensearch/tests/aws_auth.rs
opensearch/tests/client.rs
opensearch/tests/common/server.rs

Upgrades `hyper` from `0.14` to `1` in tests.

Upgrade `hyper` from `0.14` to `1` in tests

---

CHANGELOG.md
api_generator/Cargo.toml
opensearch/Cargo.toml
yaml_test_runner/Cargo.toml

Bounds `aws-*` to code-compatible versions `>=0.53,<0.57`
Fixes #223 

[Backport 2.1] Bound `aws-*` to code-compatible versions `>=0.53,<0.57`

---

api_generator/rest_specs/text_structure.find_structure.json
api_generator/src/generator/code_gen/root.rs
api_generator/src/rest_spec/mod.rs
opensearch/src/error.rs
opensearch/src/http/headers.rs
opensearch/src/http/mod.rs
opensearch/src/http/request.rs
opensearch/src/http/response.rs
opensearch/src/http/transport.rs
opensearch/src/root/bulk.rs
opensearch/src/text_structure.rs
opensearch/tests/auth.rs
opensearch/tests/common/client.rs

Replace remaining references to Elasticsearch with OpenSearch

Replace remaining references to Elasticsearch with OpenSearch

---

.github/workflows/test.yml
Makefile.toml
api_generator/src/rest_spec/mod.rs
opensearch/Cargo.toml
opensearch/src/auth.rs
opensearch/src/models/mod.rs
opensearch/tests/auth.rs
opensearch/tests/aws_auth.rs
opensearch/tests/cert.rs
opensearch/tests/client.rs
opensearch/tests/common/client.rs
opensearch/tests/common/mod.rs
opensearch/tests/common/server.rs
opensearch/tests/error.rs
yaml_test_runner/src/generator.rs
yaml_test_runner/src/github.rs
yaml_test_runner/tests/common/macros.rs

Refactors the mock HTTP server tests to simplify the test code.
Splitting up parts of #132 

Refactor mock HTTP server tests

---

CHANGELOG.md
opensearch/Cargo.toml
opensearch/src/auth.rs
opensearch/src/cert.rs
opensearch/src/error.rs
opensearch/src/http/aws_auth.rs
opensearch/src/http/mod.rs
opensearch/src/http/transport.rs

Refactors the error types to use `thiserror` and internalize the `BuildError` type.
Split from #132.

Refactor error types to use `thiserror` and internalize `BuildError`

---

CHANGELOG.md
opensearch/Cargo.toml
opensearch/src/client.rs
opensearch/src/error.rs
opensearch/src/http/middleware/initializers/client.rs
opensearch/src/http/middleware/initializers/mod.rs
opensearch/src/http/middleware/initializers/request.rs
opensearch/src/http/middleware/mod.rs
opensearch/src/http/middleware/request_handler.rs
opensearch/src/http/middleware/request_pipeline.rs
opensearch/src/http/mod.rs
opensearch/src/http/transport.rs
opensearch/tests/common/mod.rs
opensearch/tests/middleware.rs

Implement middleware types to allow intercepting client & request handling
Split from #132 

Implement middleware types to allow intercepting client & request handling

---

.github/actions/start-opensearch/action.yml
.github/workflows/test.yml

Fixes the CI to pass in "admin" as the admin password if the version is >= 2.12. This is necessary since 2.12 and onwards requires an initial admin password to be set in order to run the security demo configuration.
_List any issues this PR will resolve, e.g. Closes [...]._ 

Default admin password as admin

---

CHANGELOG.md
opensearch/Cargo.toml
yaml_test_runner/Cargo.toml

Backport 90cd340ee9decd27656efbbfd4eafad05fb00b7b from #242 

[Backport 2.x] Update base64 requirement from 0.21 to 0.22 (#242)

---

CHANGELOG.md
opensearch/src/root/bulk.rs
opensearch/tests/common/client.rs

Added new `create_no_id` and `new_no_id` constructors/helpers to support bulk create operations where no _id field is required.
Changed types to `id: Option<S>` when `_id` is optional in the bulk request, otherwise, keep `id` parameter as `String`.
This change is making the Bulk operation constructor parameters more closely match the Bulk API, specifically when `_id` is required or not.
Summarized from the docs: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docs-bulk.html#bulk-api-request-body
- `create`: `_id` (optional, string)
- `delete`: `_id` (required, string)
- `index`: `_id` (optional, string)
- `update` `_id` (required, string)
Related to, and may close issue #241 .
By submitting this pull request, I confirm that my contribution is made under the terms of the …

Add new bulk create constructor without optional _id field

---

CHANGELOG.md
opensearch/src/root/bulk.rs

Backports #245 from 28e3d47a54c4fe1ce0a3647c872411602dc6b1e2

[Backport 2.x] Add new bulk create constructor without optional _id field (#245)

---

.ci/functions/imports.sh
.ci/generate-certs.sh
.ci/run-opensearch.sh
.github/workflows/test.yml

Switch to macos-13 runner for assemble github actions due to macos-latest is now arm64
N/A

Switch to macos-13 runner for assemble github actions due to macos-latest is now arm64

---

.github/actions/run-released-opensearch/action.yml
.github/actions/start-opensearch/action.yml
.github/workflows/test.yml
opensearch/examples/cat_indices.rs
opensearch/tests/common/client.rs
yaml_test_runner/src/main.rs
yaml_test_runner/tests/common/client.rs

Update integration tests for new versions of OpenSearch

Update integration tests for new versions of OpenSearch

---

CHANGELOG.md

[Backport 2.x] Prepare changelog for 2.3.0 release (#266)

---

.github/workflows/test.yml

Switch codecov uploads to use OIDC as tokenless is no-longer supporte.
Also don't upload coverage on scheduled test runs as it skews results due to not running all tests.

Switch codecov uploads to use OIDC as tokenless is no-longer supported

---

CHANGELOG.md
opensearch/Cargo.toml
opensearch/examples/cat_indices.rs
opensearch/tests/common/client.rs
yaml_test_runner/Cargo.toml

Backport #292 via 0f27696d62ebb4b6532d37e6ba9228f9dcdfd9b6

[Backport 2.x] Update sysinfo requirement from 0.32.0 to 0.33.0 (#292)

---

.github/workflows/test.yml

Fix codecov uploading

---

CHANGELOG.md
opensearch/Cargo.toml

Changes documentation field to homepage field in Cargo.toml utilizing docs.rs docs generation while still linking to Opensearch docs as homepage.
Closes #255 .

change documentation field to homepage field in cargo.toml

---

.github/workflows/dependabot_pr.yml
CHANGELOG.md

Backport #329 via 5d16d03418fcc48fdc7d2962d03c6c9e2ecb63f3

[Backport 2.x] Bump dangoslen/dependabot-changelog-helper from 3 to 4 (#329)

---

CHANGELOG.md
opensearch/Cargo.toml
yaml_test_runner/Cargo.toml

(cherry picked from commit a3022ae9bdf47ee6b17dcd058fefb77dcb849a02)

[Backport 2.x] Update sysinfo requirement from 0.35.0 to 0.36.0 (#346)
